# -*- coding: utf-8 -*-

# Form implementation generated from reading ui file './ui_files/main_window.ui'
#
# Created: Mon Aug 24 11:16:11 2015
#      by: PyQt4 UI code generator 4.10.4
#
# WARNING! All changes made in this file will be lost!

from PyQt4 import QtCore, QtGui

try:
    _fromUtf8 = QtCore.QString.fromUtf8
except AttributeError:
    def _fromUtf8(s):
        return s

try:
    _encoding = QtGui.QApplication.UnicodeUTF8
    def _translate(context, text, disambig):
        return QtGui.QApplication.translate(context, text, disambig, _encoding)
except AttributeError:
    def _translate(context, text, disambig):
        return QtGui.QApplication.translate(context, text, disambig)

class Ui_main_window(object):
    def setupUi(self, main_window):
        main_window.setObjectName(_fromUtf8("main_window"))
        main_window.resize(890, 614)
        main_window.setMinimumSize(QtCore.QSize(890, 614))
        main_window.setMaximumSize(QtCore.QSize(890, 614))
        self.centralwidget = QtGui.QWidget(main_window)
        self.centralwidget.setObjectName(_fromUtf8("centralwidget"))
        self.frame = QtGui.QFrame(self.centralwidget)
        self.frame.setGeometry(QtCore.QRect(0, 0, 249, 588))
        self.frame.setObjectName(_fromUtf8("frame"))
        self.gridLayout_4 = QtGui.QGridLayout(self.frame)
        self.gridLayout_4.setObjectName(_fromUtf8("gridLayout_4"))
        self.gb_VideoInput = QtGui.QGroupBox(self.frame)
        self.gb_VideoInput.setMinimumSize(QtCore.QSize(231, 160))
        self.gb_VideoInput.setMaximumSize(QtCore.QSize(231, 9999))
        self.gb_VideoInput.setObjectName(_fromUtf8("gb_VideoInput"))
        self.gridLayout_3 = QtGui.QGridLayout(self.gb_VideoInput)
        self.gridLayout_3.setObjectName(_fromUtf8("gridLayout_3"))
        self.frame1 = QtGui.QFrame(self.gb_VideoInput)
        self.frame1.setObjectName(_fromUtf8("frame1"))
        self.gridLayout = QtGui.QGridLayout(self.frame1)
        self.gridLayout.setObjectName(_fromUtf8("gridLayout"))
        self.rb_fromCamera = QtGui.QRadioButton(self.frame1)
        self.rb_fromCamera.setChecked(True)
        self.rb_fromCamera.setObjectName(_fromUtf8("rb_fromCamera"))
        self.gridLayout.addWidget(self.rb_fromCamera, 0, 0, 1, 1)
        self.ledit_videoPath = QtGui.QLineEdit(self.frame1)
        self.ledit_videoPath.setEnabled(False)
        self.ledit_videoPath.setObjectName(_fromUtf8("ledit_videoPath"))
        self.gridLayout.addWidget(self.ledit_videoPath, 2, 0, 1, 1)
        self.rb_fromFile = QtGui.QRadioButton(self.frame1)
        self.rb_fromFile.setObjectName(_fromUtf8("rb_fromFile"))
        self.gridLayout.addWidget(self.rb_fromFile, 1, 0, 1, 1)
        self.btn_videoPath = QtGui.QPushButton(self.frame1)
        self.btn_videoPath.setEnabled(False)
        self.btn_videoPath.setMinimumSize(QtCore.QSize(31, 27))
        self.btn_videoPath.setMaximumSize(QtCore.QSize(31, 27))
        self.btn_videoPath.setObjectName(_fromUtf8("btn_videoPath"))
        self.gridLayout.addWidget(self.btn_videoPath, 2, 1, 1, 1)
        self.gridLayout_3.addWidget(self.frame1, 0, 0, 1, 2)
        self.btn_preview = QtGui.QPushButton(self.gb_VideoInput)
        self.btn_preview.setObjectName(_fromUtf8("btn_preview"))
        self.gridLayout_3.addWidget(self.btn_preview, 1, 0, 1, 1)
        self.btn_startAnalysis = QtGui.QPushButton(self.gb_VideoInput)
        self.btn_startAnalysis.setObjectName(_fromUtf8("btn_startAnalysis"))
        self.gridLayout_3.addWidget(self.btn_startAnalysis, 1, 1, 1, 1)
        self.gridLayout_4.addWidget(self.gb_VideoInput, 0, 0, 1, 1)
        self.gb_filtering = QtGui.QGroupBox(self.frame)
        self.gb_filtering.setEnabled(True)
        self.gb_filtering.setMinimumSize(QtCore.QSize(231, 201))
        self.gb_filtering.setMaximumSize(QtCore.QSize(231, 201))
        self.gb_filtering.setObjectName(_fromUtf8("gb_filtering"))
        self.lstview_filters = QtGui.QListView(self.gb_filtering)
        self.lstview_filters.setGeometry(QtCore.QRect(10, 20, 211, 131))
        self.lstview_filters.setObjectName(_fromUtf8("lstview_filters"))
        self.frame2 = QtGui.QFrame(self.gb_filtering)
        self.frame2.setGeometry(QtCore.QRect(0, 150, 231, 51))
        self.frame2.setObjectName(_fromUtf8("frame2"))
        self.gridLayout_2 = QtGui.QGridLayout(self.frame2)
        self.gridLayout_2.setObjectName(_fromUtf8("gridLayout_2"))
        self.label = QtGui.QLabel(self.frame2)
        self.label.setObjectName(_fromUtf8("label"))
        self.gridLayout_2.addWidget(self.label, 0, 0, 1, 1)
        self.label_2 = QtGui.QLabel(self.frame2)
        self.label_2.setObjectName(_fromUtf8("label_2"))
        self.gridLayout_2.addWidget(self.label_2, 0, 1, 1, 1, QtCore.Qt.AlignRight)
        self.scrlbar_filterValue = QtGui.QScrollBar(self.frame2)
        self.scrlbar_filterValue.setMinimum(-1000)
        self.scrlbar_filterValue.setMaximum(1000)
        self.scrlbar_filterValue.setOrientation(QtCore.Qt.Horizontal)
        self.scrlbar_filterValue.setObjectName(_fromUtf8("scrlbar_filterValue"))
        self.gridLayout_2.addWidget(self.scrlbar_filterValue, 1, 0, 1, 2)
        self.gridLayout_4.addWidget(self.gb_filtering, 1, 0, 1, 1)
        self.groupBox_4 = QtGui.QGroupBox(self.frame)
        self.groupBox_4.setEnabled(False)
        self.groupBox_4.setMinimumSize(QtCore.QSize(231, 181))
        self.groupBox_4.setMaximumSize(QtCore.QSize(231, 211))
        self.groupBox_4.setObjectName(_fromUtf8("groupBox_4"))
        self.frame_3 = QtGui.QFrame(self.groupBox_4)
        self.frame_3.setGeometry(QtCore.QRect(-10, 20, 241, 161))
        self.frame_3.setObjectName(_fromUtf8("frame_3"))
        self.gridLayout_5 = QtGui.QGridLayout(self.frame_3)
        self.gridLayout_5.setContentsMargins(21, -1, -1, -1)
        self.gridLayout_5.setObjectName(_fromUtf8("gridLayout_5"))
        self.rb_trackTrajectory = QtGui.QRadioButton(self.frame_3)
        self.rb_trackTrajectory.setObjectName(_fromUtf8("rb_trackTrajectory"))
        self.gridLayout_5.addWidget(self.rb_trackTrajectory, 3, 0, 1, 1)
        self.rb_saveBothVideoFiles = QtGui.QRadioButton(self.frame_3)
        self.rb_saveBothVideoFiles.setChecked(True)
        self.rb_saveBothVideoFiles.setObjectName(_fromUtf8("rb_saveBothVideoFiles"))
        self.gridLayout_5.addWidget(self.rb_saveBothVideoFiles, 5, 0, 1, 1)
        self.rb_notTrackTrajectory = QtGui.QRadioButton(self.frame_3)
        self.rb_notTrackTrajectory.setObjectName(_fromUtf8("rb_notTrackTrajectory"))
        self.gridLayout_5.addWidget(self.rb_notTrackTrajectory, 4, 0, 1, 1)
        self.ledit_dataOutPath = QtGui.QLineEdit(self.frame_3)
        self.ledit_dataOutPath.setEnabled(False)
        self.ledit_dataOutPath.setObjectName(_fromUtf8("ledit_dataOutPath"))
        self.gridLayout_5.addWidget(self.ledit_dataOutPath, 0, 0, 1, 1)
        self.btn_dataOutPath = QtGui.QPushButton(self.frame_3)
        self.btn_dataOutPath.setEnabled(False)
        self.btn_dataOutPath.setMinimumSize(QtCore.QSize(31, 27))
        self.btn_dataOutPath.setMaximumSize(QtCore.QSize(31, 27))
        self.btn_dataOutPath.setObjectName(_fromUtf8("btn_dataOutPath"))
        self.gridLayout_5.addWidget(self.btn_dataOutPath, 0, 1, 1, 1)
        self.cb_saveVideoFile = QtGui.QCheckBox(self.frame_3)
        self.cb_saveVideoFile.setChecked(True)
        self.cb_saveVideoFile.setObjectName(_fromUtf8("cb_saveVideoFile"))
        self.gridLayout_5.addWidget(self.cb_saveVideoFile, 2, 0, 1, 1)
        self.gridLayout_4.addWidget(self.groupBox_4, 2, 0, 1, 1)
        self.tbwidget_views = QtGui.QTabWidget(self.centralwidget)
        self.tbwidget_views.setEnabled(False)
        self.tbwidget_views.setGeometry(QtCore.QRect(250, 10, 631, 571))
        self.tbwidget_views.setObjectName(_fromUtf8("tbwidget_views"))
        self.tab_preview = QtGui.QWidget()
        self.tab_preview.setObjectName(_fromUtf8("tab_preview"))
        self.lbl_previewImage = QtGui.QLabel(self.tab_preview)
        self.lbl_previewImage.setGeometry(QtCore.QRect(10, 10, 600, 420))
        self.lbl_previewImage.setText(_fromUtf8(""))
        self.lbl_previewImage.setAlignment(QtCore.Qt.AlignCenter)
        self.lbl_previewImage.setObjectName(_fromUtf8("lbl_previewImage"))
        self.groupbox_previewControl = QtGui.QGroupBox(self.tab_preview)
        self.groupbox_previewControl.setEnabled(False)
        self.groupbox_previewControl.setGeometry(QtCore.QRect(10, 440, 611, 91))
        self.groupbox_previewControl.setObjectName(_fromUtf8("groupbox_previewControl"))
        self.pushButton = QtGui.QPushButton(self.groupbox_previewControl)
        self.pushButton.setGeometry(QtCore.QRect(480, 20, 121, 61))
        self.pushButton.setObjectName(_fromUtf8("pushButton"))
        self.scrlbar_previewTime = QtGui.QScrollBar(self.groupbox_previewControl)
        self.scrlbar_previewTime.setEnabled(False)
        self.scrlbar_previewTime.setGeometry(QtCore.QRect(110, 40, 361, 41))
        self.scrlbar_previewTime.setTracking(True)
        self.scrlbar_previewTime.setOrientation(QtCore.Qt.Horizontal)
        self.scrlbar_previewTime.setObjectName(_fromUtf8("scrlbar_previewTime"))
        self.btn_previewPlayPause = QtGui.QPushButton(self.groupbox_previewControl)
        self.btn_previewPlayPause.setEnabled(False)
        self.btn_previewPlayPause.setGeometry(QtCore.QRect(10, 20, 91, 61))
        self.btn_previewPlayPause.setCheckable(True)
        self.btn_previewPlayPause.setChecked(False)
        self.btn_previewPlayPause.setObjectName(_fromUtf8("btn_previewPlayPause"))
        self.lbl_previewTime = QtGui.QLabel(self.groupbox_previewControl)
        self.lbl_previewTime.setEnabled(False)
        self.lbl_previewTime.setGeometry(QtCore.QRect(260, 20, 53, 17))
        self.lbl_previewTime.setObjectName(_fromUtf8("lbl_previewTime"))
        self.tbwidget_views.addTab(self.tab_preview, _fromUtf8(""))
        self.tab_view = QtGui.QWidget()
        self.tab_view.setObjectName(_fromUtf8("tab_view"))
        self.tbwidget_views.addTab(self.tab_view, _fromUtf8(""))
        self.tab_reports = QtGui.QWidget()
        self.tab_reports.setObjectName(_fromUtf8("tab_reports"))
        self.tbwidget_views.addTab(self.tab_reports, _fromUtf8(""))
        main_window.setCentralWidget(self.centralwidget)
        self.menubar = QtGui.QMenuBar(main_window)
        self.menubar.setGeometry(QtCore.QRect(0, 0, 890, 25))
        self.menubar.setObjectName(_fromUtf8("menubar"))
        self.menuAn_lise = QtGui.QMenu(self.menubar)
        self.menuAn_lise.setObjectName(_fromUtf8("menuAn_lise"))
        self.menuAjuda = QtGui.QMenu(self.menubar)
        self.menuAjuda.setObjectName(_fromUtf8("menuAjuda"))
        main_window.setMenuBar(self.menubar)
        self.menu_newAnalysis = QtGui.QAction(main_window)
        self.menu_newAnalysis.setObjectName(_fromUtf8("menu_newAnalysis"))
        self.mn_Export = QtGui.QAction(main_window)
        self.mn_Export.setEnabled(False)
        self.mn_Export.setObjectName(_fromUtf8("mn_Export"))
        self.mn_userManual = QtGui.QAction(main_window)
        self.mn_userManual.setObjectName(_fromUtf8("mn_userManual"))
        self.mn_about = QtGui.QAction(main_window)
        self.mn_about.setObjectName(_fromUtf8("mn_about"))
        self.mnExit = QtGui.QAction(main_window)
        self.mnExit.setObjectName(_fromUtf8("mnExit"))
        self.menuAn_lise.addAction(self.menu_newAnalysis)
        self.menuAn_lise.addSeparator()
        self.menuAn_lise.addAction(self.mn_Export)
        self.menuAn_lise.addSeparator()
        self.menuAn_lise.addAction(self.mnExit)
        self.menuAjuda.addAction(self.mn_userManual)
        self.menuAjuda.addSeparator()
        self.menuAjuda.addAction(self.mn_about)
        self.menubar.addAction(self.menuAn_lise.menuAction())
        self.menubar.addAction(self.menuAjuda.menuAction())

        self.retranslateUi(main_window)
        self.tbwidget_views.setCurrentIndex(2)
        QtCore.QObject.connect(self.scrlbar_filterValue, QtCore.SIGNAL(_fromUtf8("valueChanged(int)")), self.label_2.setNum)
        QtCore.QMetaObject.connectSlotsByName(main_window)

    def retranslateUi(self, main_window):
        main_window.setWindowTitle(_translate("main_window", "Ferramenta Visual de Análise Cinemática", None))
        self.gb_VideoInput.setTitle(_translate("main_window", "Entrada de Vídeo", None))
        self.rb_fromCamera.setText(_translate("main_window", "Da Câmera", None))
        self.rb_fromFile.setText(_translate("main_window", "Do Arquivo", None))
        self.btn_videoPath.setText(_translate("main_window", "...", None))
        self.btn_preview.setText(_translate("main_window", "Pré-Visualizar", None))
        self.btn_startAnalysis.setText(_translate("main_window", "Iniciar Análise", None))
        self.gb_filtering.setTitle(_translate("main_window", "Filtros e Técnicas de Filtragem", None))
        self.label.setText(_translate("main_window", "Valor", None))
        self.label_2.setText(_translate("main_window", "0", None))
        self.groupBox_4.setTitle(_translate("main_window", "Saída de Dados", None))
        self.rb_trackTrajectory.setText(_translate("main_window", "Traçar Trajetória", None))
        self.rb_saveBothVideoFiles.setText(_translate("main_window", "Ambos(Dois Arquivos)", None))
        self.rb_notTrackTrajectory.setText(_translate("main_window", "Não Traçar Trajetória", None))
        self.btn_dataOutPath.setText(_translate("main_window", "...", None))
        self.cb_saveVideoFile.setText(_translate("main_window", "Salvar Arquivo de Vídeo", None))
        self.groupbox_previewControl.setTitle(_translate("main_window", "Controle de Pré-Visualização", None))
        self.pushButton.setText(_translate("main_window", "Iniciar Análise", None))
        self.btn_previewPlayPause.setText(_translate("main_window", "Play", None))
        self.lbl_previewTime.setText(_translate("main_window", "0:00:00", None))
        self.tbwidget_views.setTabText(self.tbwidget_views.indexOf(self.tab_preview), _translate("main_window", "Pré-Visualização", None))
        self.tbwidget_views.setTabText(self.tbwidget_views.indexOf(self.tab_view), _translate("main_window", "Visualização", None))
        self.tbwidget_views.setTabText(self.tbwidget_views.indexOf(self.tab_reports), _translate("main_window", "Análise e Relatórios", None))
        self.menuAn_lise.setTitle(_translate("main_window", "Análise", None))
        self.menuAjuda.setTitle(_translate("main_window", "Ajuda", None))
        self.menu_newAnalysis.setText(_translate("main_window", "Nova Análise", None))
        self.mn_Export.setText(_translate("main_window", "Exportar", None))
        self.mn_userManual.setText(_translate("main_window", "Manual do Usuário", None))
        self.mn_about.setText(_translate("main_window", "Sobre", None))
        self.mnExit.setText(_translate("main_window", "Sair", None))


if __name__ == "__main__":
    import sys
    app = QtGui.QApplication(sys.argv)
    main_window = QtGui.QMainWindow()
    ui = Ui_main_window()
    ui.setupUi(main_window)
    main_window.show()
    sys.exit(app.exec_())

