# -*- coding: utf-8 -*-

# Form implementation generated from reading ui file './qt4-ui_files/QWizard_NewAnalysis.ui'
#
# Created: Sun Oct 25 00:50:58 2015
#      by: PyQt4 UI code generator 4.10.4
#
# WARNING! All changes made in this file will be lost!

from PyQt4 import QtCore, QtGui

try:
    _fromUtf8 = QtCore.QString.fromUtf8
except AttributeError:
    def _fromUtf8(s):
        return s

try:
    _encoding = QtGui.QApplication.UnicodeUTF8
    def _translate(context, text, disambig):
        return QtGui.QApplication.translate(context, text, disambig, _encoding)
except AttributeError:
    def _translate(context, text, disambig):
        return QtGui.QApplication.translate(context, text, disambig)

class Ui_QWizard_NewAnalysis(object):
    def setupUi(self, QWizard_NewAnalysis):
        QWizard_NewAnalysis.setObjectName(_fromUtf8("QWizard_NewAnalysis"))
        QWizard_NewAnalysis.setWindowModality(QtCore.Qt.WindowModal)
        QWizard_NewAnalysis.resize(698, 621)
        QWizard_NewAnalysis.setMinimumSize(QtCore.QSize(640, 480))
        QWizard_NewAnalysis.setMaximumSize(QtCore.QSize(999999, 524287))
        QWizard_NewAnalysis.setWizardStyle(QtGui.QWizard.ClassicStyle)
        QWizard_NewAnalysis.setOptions(QtGui.QWizard.HelpButtonOnRight)
        self.wzdp_videoInput = QWizardPage_VideoInput()
        self.wzdp_videoInput.setObjectName(_fromUtf8("wzdp_videoInput"))
        self.gridLayout_2 = QtGui.QGridLayout(self.wzdp_videoInput)
        self.gridLayout_2.setObjectName(_fromUtf8("gridLayout_2"))
        self.frame = QtGui.QFrame(self.wzdp_videoInput)
        self.frame.setMaximumSize(QtCore.QSize(16777215, 176))
        self.frame.setObjectName(_fromUtf8("frame"))
        self.verticalLayout = QtGui.QVBoxLayout(self.frame)
        self.verticalLayout.setObjectName(_fromUtf8("verticalLayout"))
        self.label_6 = QtGui.QLabel(self.frame)
        self.label_6.setMaximumSize(QtCore.QSize(16777215, 45))
        font = QtGui.QFont()
        font.setPointSize(10)
        font.setBold(True)
        font.setWeight(75)
        self.label_6.setFont(font)
        self.label_6.setAlignment(QtCore.Qt.AlignLeading|QtCore.Qt.AlignLeft|QtCore.Qt.AlignVCenter)
        self.label_6.setObjectName(_fromUtf8("label_6"))
        self.verticalLayout.addWidget(self.label_6)
        self.rb_fromCamera = QtGui.QRadioButton(self.frame)
        self.rb_fromCamera.setEnabled(False)
        self.rb_fromCamera.setMaximumSize(QtCore.QSize(16777215, 29))
        font = QtGui.QFont()
        font.setPointSize(10)
        self.rb_fromCamera.setFont(font)
        self.rb_fromCamera.setChecked(False)
        self.rb_fromCamera.setObjectName(_fromUtf8("rb_fromCamera"))
        self.verticalLayout.addWidget(self.rb_fromCamera)
        self.rb_fromFile = QtGui.QRadioButton(self.frame)
        self.rb_fromFile.setMaximumSize(QtCore.QSize(16777215, 29))
        font = QtGui.QFont()
        font.setPointSize(10)
        self.rb_fromFile.setFont(font)
        self.rb_fromFile.setChecked(True)
        self.rb_fromFile.setObjectName(_fromUtf8("rb_fromFile"))
        self.verticalLayout.addWidget(self.rb_fromFile)
        self.frame_VideoPath = QtGui.QFrame(self.frame)
        self.frame_VideoPath.setMaximumSize(QtCore.QSize(16777215, 81))
        self.frame_VideoPath.setObjectName(_fromUtf8("frame_VideoPath"))
        self.gridLayout = QtGui.QGridLayout(self.frame_VideoPath)
        self.gridLayout.setContentsMargins(5, 10, 5, 10)
        self.gridLayout.setObjectName(_fromUtf8("gridLayout"))
        self.label_2 = QtGui.QLabel(self.frame_VideoPath)
        font = QtGui.QFont()
        font.setPointSize(10)
        self.label_2.setFont(font)
        self.label_2.setObjectName(_fromUtf8("label_2"))
        self.gridLayout.addWidget(self.label_2, 0, 0, 1, 1)
        self.pb_searchFile = QtGui.QPushButton(self.frame_VideoPath)
        self.pb_searchFile.setMinimumSize(QtCore.QSize(31, 21))
        self.pb_searchFile.setMaximumSize(QtCore.QSize(31, 21))
        font = QtGui.QFont()
        font.setPointSize(10)
        self.pb_searchFile.setFont(font)
        self.pb_searchFile.setObjectName(_fromUtf8("pb_searchFile"))
        self.gridLayout.addWidget(self.pb_searchFile, 2, 1, 1, 1)
        self.ledit_videoPath = QtGui.QLineEdit(self.frame_VideoPath)
        self.ledit_videoPath.setMinimumSize(QtCore.QSize(217, 23))
        font = QtGui.QFont()
        font.setPointSize(10)
        self.ledit_videoPath.setFont(font)
        self.ledit_videoPath.setObjectName(_fromUtf8("ledit_videoPath"))
        self.gridLayout.addWidget(self.ledit_videoPath, 2, 0, 1, 1)
        self.verticalLayout.addWidget(self.frame_VideoPath)
        self.gridLayout_2.addWidget(self.frame, 0, 0, 1, 1)
        QWizard_NewAnalysis.addPage(self.wzdp_videoInput)
        self.wzdp_dimensionalRatio = QWizardPage_DimensionalRatio()
        self.wzdp_dimensionalRatio.setEnabled(True)
        self.wzdp_dimensionalRatio.setObjectName(_fromUtf8("wzdp_dimensionalRatio"))
        self.tckbar_frame = QtGui.QScrollBar(self.wzdp_dimensionalRatio)
        self.tckbar_frame.setEnabled(True)
        self.tckbar_frame.setGeometry(QtCore.QRect(127, 500, 551, 31))
        palette = QtGui.QPalette()
        brush = QtGui.QBrush(QtGui.QColor(0, 0, 0))
        brush.setStyle(QtCore.Qt.SolidPattern)
        palette.setBrush(QtGui.QPalette.Active, QtGui.QPalette.WindowText, brush)
        brush = QtGui.QBrush(QtGui.QColor(55, 255, 0))
        brush.setStyle(QtCore.Qt.SolidPattern)
        palette.setBrush(QtGui.QPalette.Active, QtGui.QPalette.Button, brush)
        brush = QtGui.QBrush(QtGui.QColor(2, 139, 0))
        brush.setStyle(QtCore.Qt.SolidPattern)
        palette.setBrush(QtGui.QPalette.Active, QtGui.QPalette.Base, brush)
        brush = QtGui.QBrush(QtGui.QColor(0, 0, 0))
        brush.setStyle(QtCore.Qt.SolidPattern)
        palette.setBrush(QtGui.QPalette.Inactive, QtGui.QPalette.WindowText, brush)
        brush = QtGui.QBrush(QtGui.QColor(55, 255, 0))
        brush.setStyle(QtCore.Qt.SolidPattern)
        palette.setBrush(QtGui.QPalette.Inactive, QtGui.QPalette.Button, brush)
        brush = QtGui.QBrush(QtGui.QColor(2, 139, 0))
        brush.setStyle(QtCore.Qt.SolidPattern)
        palette.setBrush(QtGui.QPalette.Inactive, QtGui.QPalette.Base, brush)
        brush = QtGui.QBrush(QtGui.QColor(123, 123, 123))
        brush.setStyle(QtCore.Qt.SolidPattern)
        palette.setBrush(QtGui.QPalette.Disabled, QtGui.QPalette.WindowText, brush)
        brush = QtGui.QBrush(QtGui.QColor(55, 255, 0))
        brush.setStyle(QtCore.Qt.SolidPattern)
        palette.setBrush(QtGui.QPalette.Disabled, QtGui.QPalette.Button, brush)
        brush = QtGui.QBrush(QtGui.QColor(243, 243, 243))
        brush.setStyle(QtCore.Qt.SolidPattern)
        palette.setBrush(QtGui.QPalette.Disabled, QtGui.QPalette.Base, brush)
        self.tckbar_frame.setPalette(palette)
        self.tckbar_frame.setOrientation(QtCore.Qt.Horizontal)
        self.tckbar_frame.setObjectName(_fromUtf8("tckbar_frame"))
        self.gv_lineMarker = QGraphicsView_LineMarker(self.wzdp_dimensionalRatio)
        self.gv_lineMarker.setGeometry(QtCore.QRect(0, 140, 681, 351))
        self.gv_lineMarker.setObjectName(_fromUtf8("gv_lineMarker"))
        self.layoutWidget = QtGui.QWidget(self.wzdp_dimensionalRatio)
        self.layoutWidget.setGeometry(QtCore.QRect(0, 0, 2, 2))
        self.layoutWidget.setObjectName(_fromUtf8("layoutWidget"))
        self.verticalLayout_2 = QtGui.QVBoxLayout(self.layoutWidget)
        self.verticalLayout_2.setMargin(0)
        self.verticalLayout_2.setObjectName(_fromUtf8("verticalLayout_2"))
        self.frame_2 = QtGui.QFrame(self.wzdp_dimensionalRatio)
        self.frame_2.setGeometry(QtCore.QRect(0, 0, 681, 141))
        self.frame_2.setObjectName(_fromUtf8("frame_2"))
        self.gridLayout_3 = QtGui.QGridLayout(self.frame_2)
        self.gridLayout_3.setObjectName(_fromUtf8("gridLayout_3"))
        self.tabWidget = QtGui.QTabWidget(self.frame_2)
        self.tabWidget.setMinimumSize(QtCore.QSize(663, 123))
        self.tabWidget.setMaximumSize(QtCore.QSize(111111, 16777215))
        self.tabWidget.setTabPosition(QtGui.QTabWidget.South)
        self.tabWidget.setObjectName(_fromUtf8("tabWidget"))
        self.tab = QtGui.QWidget()
        self.tab.setObjectName(_fromUtf8("tab"))
        self.frame_3 = QtGui.QFrame(self.tab)
        self.frame_3.setGeometry(QtCore.QRect(10, 10, 92, 81))
        self.frame_3.setMinimumSize(QtCore.QSize(92, 76))
        self.frame_3.setMaximumSize(QtCore.QSize(92, 81))
        self.frame_3.setFrameShape(QtGui.QFrame.StyledPanel)
        self.frame_3.setFrameShadow(QtGui.QFrame.Raised)
        self.frame_3.setObjectName(_fromUtf8("frame_3"))
        self.gridLayout_4 = QtGui.QGridLayout(self.frame_3)
        self.gridLayout_4.setObjectName(_fromUtf8("gridLayout_4"))
        self.lbl_color = QLabel_Color(self.frame_3)
        self.lbl_color.setMinimumSize(QtCore.QSize(32, 32))
        self.lbl_color.setMaximumSize(QtCore.QSize(32, 32))
        self.lbl_color.setFrameShape(QtGui.QFrame.Box)
        self.lbl_color.setText(_fromUtf8(""))
        self.lbl_color.setAlignment(QtCore.Qt.AlignCenter)
        self.lbl_color.setObjectName(_fromUtf8("lbl_color"))
        self.gridLayout_4.addWidget(self.lbl_color, 0, 0, 1, 1, QtCore.Qt.AlignHCenter)
        self.label = QtGui.QLabel(self.frame_3)
        self.label.setObjectName(_fromUtf8("label"))
        self.gridLayout_4.addWidget(self.label, 1, 0, 1, 1, QtCore.Qt.AlignHCenter)
        self.frame_4 = QtGui.QFrame(self.tab)
        self.frame_4.setGeometry(QtCore.QRect(110, 10, 531, 81))
        self.frame_4.setFrameShape(QtGui.QFrame.StyledPanel)
        self.frame_4.setFrameShadow(QtGui.QFrame.Raised)
        self.frame_4.setObjectName(_fromUtf8("frame_4"))
        self.gridLayout_5 = QtGui.QGridLayout(self.frame_4)
        self.gridLayout_5.setObjectName(_fromUtf8("gridLayout_5"))
        self.label_3 = QtGui.QLabel(self.frame_4)
        self.label_3.setObjectName(_fromUtf8("label_3"))
        self.gridLayout_5.addWidget(self.label_3, 0, 0, 1, 1, QtCore.Qt.AlignHCenter)
        self.label_4 = QtGui.QLabel(self.frame_4)
        self.label_4.setObjectName(_fromUtf8("label_4"))
        self.gridLayout_5.addWidget(self.label_4, 0, 1, 1, 1, QtCore.Qt.AlignHCenter)
        self.lbl_lineLength = QtGui.QLabel(self.frame_4)
        self.lbl_lineLength.setObjectName(_fromUtf8("lbl_lineLength"))
        self.gridLayout_5.addWidget(self.lbl_lineLength, 1, 0, 1, 1, QtCore.Qt.AlignHCenter)
        self.le_realLength = QtGui.QLineEdit(self.frame_4)
        self.le_realLength.setMaximumSize(QtCore.QSize(100, 16777215))
        self.le_realLength.setObjectName(_fromUtf8("le_realLength"))
        self.gridLayout_5.addWidget(self.le_realLength, 1, 1, 1, 1, QtCore.Qt.AlignHCenter)
        self.tabWidget.addTab(self.tab, _fromUtf8(""))
        self.tab_2 = QtGui.QWidget()
        self.tab_2.setObjectName(_fromUtf8("tab_2"))
        self.gridLayout_6 = QtGui.QGridLayout(self.tab_2)
        self.gridLayout_6.setObjectName(_fromUtf8("gridLayout_6"))
        self.pushButton = QtGui.QPushButton(self.tab_2)
        self.pushButton.setEnabled(False)
        self.pushButton.setObjectName(_fromUtf8("pushButton"))
        self.gridLayout_6.addWidget(self.pushButton, 0, 0, 1, 1)
        self.pb_saveFilters = QtGui.QPushButton(self.tab_2)
        self.pb_saveFilters.setObjectName(_fromUtf8("pb_saveFilters"))
        self.gridLayout_6.addWidget(self.pb_saveFilters, 0, 1, 1, 1)
        self.pushButton_2 = QtGui.QPushButton(self.tab_2)
        self.pushButton_2.setEnabled(False)
        self.pushButton_2.setObjectName(_fromUtf8("pushButton_2"))
        self.gridLayout_6.addWidget(self.pushButton_2, 1, 0, 1, 1)
        self.pb_editFilters = QtGui.QPushButton(self.tab_2)
        self.pb_editFilters.setObjectName(_fromUtf8("pb_editFilters"))
        self.gridLayout_6.addWidget(self.pb_editFilters, 1, 1, 1, 1)
        self.tabWidget.addTab(self.tab_2, _fromUtf8(""))
        self.tab_5 = QtGui.QWidget()
        self.tab_5.setObjectName(_fromUtf8("tab_5"))
        self.label_5 = QtGui.QLabel(self.tab_5)
        self.label_5.setGeometry(QtCore.QRect(10, 10, 231, 17))
        self.label_5.setObjectName(_fromUtf8("label_5"))
        self.spbox_posY = QtGui.QSpinBox(self.tab_5)
        self.spbox_posY.setGeometry(QtCore.QRect(140, 50, 71, 23))
        self.spbox_posY.setAccelerated(True)
        self.spbox_posY.setMaximum(10000)
        self.spbox_posY.setObjectName(_fromUtf8("spbox_posY"))
        self.label_7 = QtGui.QLabel(self.tab_5)
        self.label_7.setGeometry(QtCore.QRect(50, 30, 16, 17))
        self.label_7.setObjectName(_fromUtf8("label_7"))
        self.label_8 = QtGui.QLabel(self.tab_5)
        self.label_8.setGeometry(QtCore.QRect(170, 30, 16, 17))
        self.label_8.setObjectName(_fromUtf8("label_8"))
        self.spbox_posX = QtGui.QSpinBox(self.tab_5)
        self.spbox_posX.setGeometry(QtCore.QRect(20, 50, 71, 23))
        self.spbox_posX.setAccelerated(True)
        self.spbox_posX.setObjectName(_fromUtf8("spbox_posX"))
        self.label_9 = QtGui.QLabel(self.tab_5)
        self.label_9.setGeometry(QtCore.QRect(250, 10, 161, 17))
        self.label_9.setObjectName(_fromUtf8("label_9"))
        self.spbox_rotAng = QtGui.QSpinBox(self.tab_5)
        self.spbox_rotAng.setGeometry(QtCore.QRect(300, 50, 48, 23))
        self.spbox_rotAng.setButtonSymbols(QtGui.QAbstractSpinBox.PlusMinus)
        self.spbox_rotAng.setAccelerated(True)
        self.spbox_rotAng.setObjectName(_fromUtf8("spbox_rotAng"))
        self.cb_showCoordsSystem = QtGui.QCheckBox(self.tab_5)
        self.cb_showCoordsSystem.setGeometry(QtCore.QRect(430, 10, 201, 22))
        self.cb_showCoordsSystem.setObjectName(_fromUtf8("cb_showCoordsSystem"))
        self.tabWidget.addTab(self.tab_5, _fromUtf8(""))
        self.gridLayout_3.addWidget(self.tabWidget, 0, 0, 1, 1)
        self.lbl_frame = QtGui.QLabel(self.wzdp_dimensionalRatio)
        self.lbl_frame.setEnabled(True)
        self.lbl_frame.setGeometry(QtCore.QRect(0, 500, 121, 30))
        self.lbl_frame.setAlignment(QtCore.Qt.AlignCenter)
        self.lbl_frame.setTextInteractionFlags(QtCore.Qt.LinksAccessibleByMouse)
        self.lbl_frame.setObjectName(_fromUtf8("lbl_frame"))
        QWizard_NewAnalysis.addPage(self.wzdp_dimensionalRatio)

        self.retranslateUi(QWizard_NewAnalysis)
        self.tabWidget.setCurrentIndex(2)
        QtCore.QObject.connect(self.rb_fromFile, QtCore.SIGNAL(_fromUtf8("toggled(bool)")), self.frame_VideoPath.setVisible)
        QtCore.QMetaObject.connectSlotsByName(QWizard_NewAnalysis)

    def retranslateUi(self, QWizard_NewAnalysis):
        QWizard_NewAnalysis.setWindowTitle(_translate("QWizard_NewAnalysis", "Nova Análise", None))
        self.label_6.setText(_translate("QWizard_NewAnalysis", "Selecione o tipo de entrada de vídeo a ser utilizada na análise", None))
        self.rb_fromCamera.setText(_translate("QWizard_NewAnalysis", "Câmera", None))
        self.rb_fromFile.setText(_translate("QWizard_NewAnalysis", "Arquivo de Vídeo", None))
        self.label_2.setText(_translate("QWizard_NewAnalysis", "Caminho do Arquivo de Vídeo:", None))
        self.pb_searchFile.setText(_translate("QWizard_NewAnalysis", "...", None))
        self.label.setText(_translate("QWizard_NewAnalysis", "Cor da Linha", None))
        self.label_3.setText(_translate("QWizard_NewAnalysis", "Dimensão da Linha em Pixels", None))
        self.label_4.setText(_translate("QWizard_NewAnalysis", "Dimensão Real da Linha (mm)", None))
        self.lbl_lineLength.setText(_translate("QWizard_NewAnalysis", "0", None))
        self.tabWidget.setTabText(self.tabWidget.indexOf(self.tab), _translate("QWizard_NewAnalysis", "Linha Dimensional", None))
        self.pushButton.setText(_translate("QWizard_NewAnalysis", "Carregar Arquivo de Parâmetros", None))
        self.pb_saveFilters.setText(_translate("QWizard_NewAnalysis", "Salvar Parâmetros", None))
        self.pushButton_2.setText(_translate("QWizard_NewAnalysis", "Importar Arquivo de Parâmetros", None))
        self.pb_editFilters.setText(_translate("QWizard_NewAnalysis", "Editar Parâmetros", None))
        self.tabWidget.setTabText(self.tabWidget.indexOf(self.tab_2), _translate("QWizard_NewAnalysis", "Filtros", None))
        self.label_5.setText(_translate("QWizard_NewAnalysis", "Posição da Origem do Sistema (Em Pixels)", None))
        self.spbox_posY.setSuffix(_translate("QWizard_NewAnalysis", " px", None))
        self.label_7.setText(_translate("QWizard_NewAnalysis", "x", None))
        self.label_8.setText(_translate("QWizard_NewAnalysis", "y", None))
        self.spbox_posX.setSuffix(_translate("QWizard_NewAnalysis", " px", None))
        self.label_9.setText(_translate("QWizard_NewAnalysis", "Inclinação do Sistema (Graus)", None))
        self.spbox_rotAng.setSuffix(_translate("QWizard_NewAnalysis", " º", None))
        self.cb_showCoordsSystem.setText(_translate("QWizard_NewAnalysis", "Mostrar o sistema na visualização", None))
        self.tabWidget.setTabText(self.tabWidget.indexOf(self.tab_5), _translate("QWizard_NewAnalysis", "Sistema de Coordenadas", None))
        self.lbl_frame.setText(_translate("QWizard_NewAnalysis", "0", None))

from QGraphicsView_LineMarker import QGraphicsView_LineMarker
from QWizardPage_DimensionalRatio import QWizardPage_DimensionalRatio
from QWizardPage_VideoInput import QWizardPage_VideoInput
from QLabel_Color import QLabel_Color
