# -*- coding: utf-8 -*-

# Form implementation generated from reading ui file './qt4-ui_files/QWizard_NewAnalysis.ui'
#
# Created: Thu Oct  1 21:47:09 2015
#      by: PyQt4 UI code generator 4.10.4
#
# WARNING! All changes made in this file will be lost!

from PyQt4 import QtCore, QtGui

try:
    _fromUtf8 = QtCore.QString.fromUtf8
except AttributeError:
    def _fromUtf8(s):
        return s

try:
    _encoding = QtGui.QApplication.UnicodeUTF8
    def _translate(context, text, disambig):
        return QtGui.QApplication.translate(context, text, disambig, _encoding)
except AttributeError:
    def _translate(context, text, disambig):
        return QtGui.QApplication.translate(context, text, disambig)

class Ui_QWizard_NewAnalysis(object):
    def setupUi(self, QWizard_NewAnalysis):
        QWizard_NewAnalysis.setObjectName(_fromUtf8("QWizard_NewAnalysis"))
        QWizard_NewAnalysis.setWindowModality(QtCore.Qt.WindowModal)
        QWizard_NewAnalysis.resize(702, 621)
        QWizard_NewAnalysis.setMinimumSize(QtCore.QSize(640, 480))
        QWizard_NewAnalysis.setMaximumSize(QtCore.QSize(999999, 524287))
        QWizard_NewAnalysis.setWizardStyle(QtGui.QWizard.ClassicStyle)
        QWizard_NewAnalysis.setOptions(QtGui.QWizard.HelpButtonOnRight)
        self.wzdp_videoInput = QWizardPage_VideoInput()
        self.wzdp_videoInput.setObjectName(_fromUtf8("wzdp_videoInput"))
        self.gridLayout_2 = QtGui.QGridLayout(self.wzdp_videoInput)
        self.gridLayout_2.setObjectName(_fromUtf8("gridLayout_2"))
        self.frame = QtGui.QFrame(self.wzdp_videoInput)
        self.frame.setMaximumSize(QtCore.QSize(16777215, 176))
        self.frame.setObjectName(_fromUtf8("frame"))
        self.verticalLayout = QtGui.QVBoxLayout(self.frame)
        self.verticalLayout.setObjectName(_fromUtf8("verticalLayout"))
        self.label_6 = QtGui.QLabel(self.frame)
        self.label_6.setMaximumSize(QtCore.QSize(16777215, 45))
        font = QtGui.QFont()
        font.setPointSize(10)
        font.setBold(True)
        font.setWeight(75)
        self.label_6.setFont(font)
        self.label_6.setAlignment(QtCore.Qt.AlignLeading|QtCore.Qt.AlignLeft|QtCore.Qt.AlignVCenter)
        self.label_6.setObjectName(_fromUtf8("label_6"))
        self.verticalLayout.addWidget(self.label_6)
        self.rb_fromCamera = QtGui.QRadioButton(self.frame)
        self.rb_fromCamera.setMaximumSize(QtCore.QSize(16777215, 29))
        font = QtGui.QFont()
        font.setPointSize(10)
        self.rb_fromCamera.setFont(font)
        self.rb_fromCamera.setChecked(False)
        self.rb_fromCamera.setObjectName(_fromUtf8("rb_fromCamera"))
        self.verticalLayout.addWidget(self.rb_fromCamera)
        self.rb_fromFile = QtGui.QRadioButton(self.frame)
        self.rb_fromFile.setMaximumSize(QtCore.QSize(16777215, 29))
        font = QtGui.QFont()
        font.setPointSize(10)
        self.rb_fromFile.setFont(font)
        self.rb_fromFile.setChecked(True)
        self.rb_fromFile.setObjectName(_fromUtf8("rb_fromFile"))
        self.verticalLayout.addWidget(self.rb_fromFile)
        self.frame_VideoPath = QtGui.QFrame(self.frame)
        self.frame_VideoPath.setMaximumSize(QtCore.QSize(16777215, 81))
        self.frame_VideoPath.setObjectName(_fromUtf8("frame_VideoPath"))
        self.gridLayout = QtGui.QGridLayout(self.frame_VideoPath)
        self.gridLayout.setContentsMargins(5, 10, 5, 10)
        self.gridLayout.setObjectName(_fromUtf8("gridLayout"))
        self.label_2 = QtGui.QLabel(self.frame_VideoPath)
        font = QtGui.QFont()
        font.setPointSize(10)
        self.label_2.setFont(font)
        self.label_2.setObjectName(_fromUtf8("label_2"))
        self.gridLayout.addWidget(self.label_2, 0, 0, 1, 1)
        self.pb_searchFile = QtGui.QPushButton(self.frame_VideoPath)
        self.pb_searchFile.setMinimumSize(QtCore.QSize(31, 21))
        self.pb_searchFile.setMaximumSize(QtCore.QSize(31, 21))
        font = QtGui.QFont()
        font.setPointSize(10)
        self.pb_searchFile.setFont(font)
        self.pb_searchFile.setObjectName(_fromUtf8("pb_searchFile"))
        self.gridLayout.addWidget(self.pb_searchFile, 2, 1, 1, 1)
        self.ledit_videoPath = QtGui.QLineEdit(self.frame_VideoPath)
        self.ledit_videoPath.setMinimumSize(QtCore.QSize(217, 23))
        font = QtGui.QFont()
        font.setPointSize(10)
        self.ledit_videoPath.setFont(font)
        self.ledit_videoPath.setObjectName(_fromUtf8("ledit_videoPath"))
        self.gridLayout.addWidget(self.ledit_videoPath, 2, 0, 1, 1)
        self.verticalLayout.addWidget(self.frame_VideoPath)
        self.gridLayout_2.addWidget(self.frame, 0, 0, 1, 1)
        QWizard_NewAnalysis.addPage(self.wzdp_videoInput)
        self.wzdp_dimensionalRatio = QWizardPage_DimensionalRatio()
        self.wzdp_dimensionalRatio.setObjectName(_fromUtf8("wzdp_dimensionalRatio"))
        self.tckbar_frame = QtGui.QScrollBar(self.wzdp_dimensionalRatio)
        self.tckbar_frame.setEnabled(True)
        self.tckbar_frame.setGeometry(QtCore.QRect(0, 374, 681, 31))
        palette = QtGui.QPalette()
        brush = QtGui.QBrush(QtGui.QColor(28, 141, 163))
        brush.setStyle(QtCore.Qt.SolidPattern)
        palette.setBrush(QtGui.QPalette.Active, QtGui.QPalette.Button, brush)
        brush = QtGui.QBrush(QtGui.QColor(28, 141, 163))
        brush.setStyle(QtCore.Qt.SolidPattern)
        palette.setBrush(QtGui.QPalette.Inactive, QtGui.QPalette.Button, brush)
        brush = QtGui.QBrush(QtGui.QColor(28, 141, 163))
        brush.setStyle(QtCore.Qt.SolidPattern)
        palette.setBrush(QtGui.QPalette.Disabled, QtGui.QPalette.Button, brush)
        self.tckbar_frame.setPalette(palette)
        self.tckbar_frame.setOrientation(QtCore.Qt.Horizontal)
        self.tckbar_frame.setObjectName(_fromUtf8("tckbar_frame"))
        self.gv_lineMarker = QGraphicsView_LineMarker(self.wzdp_dimensionalRatio)
        self.gv_lineMarker.setGeometry(QtCore.QRect(0, 40, 681, 331))
        self.gv_lineMarker.setObjectName(_fromUtf8("gv_lineMarker"))
        self.pb_holdFrame = QtGui.QPushButton(self.wzdp_dimensionalRatio)
        self.pb_holdFrame.setGeometry(QtCore.QRect(0, 376, 681, 27))
        self.pb_holdFrame.setCheckable(True)
        self.pb_holdFrame.setObjectName(_fromUtf8("pb_holdFrame"))
        self.label_10 = QtGui.QLabel(self.wzdp_dimensionalRatio)
        self.label_10.setGeometry(QtCore.QRect(0, 0, 648, 31))
        self.label_10.setMaximumSize(QtCore.QSize(16777215, 45))
        font = QtGui.QFont()
        font.setPointSize(10)
        font.setBold(True)
        font.setWeight(75)
        self.label_10.setFont(font)
        self.label_10.setAlignment(QtCore.Qt.AlignLeading|QtCore.Qt.AlignLeft|QtCore.Qt.AlignVCenter)
        self.label_10.setWordWrap(True)
        self.label_10.setObjectName(_fromUtf8("label_10"))
        self.frame_2 = QtGui.QFrame(self.wzdp_dimensionalRatio)
        self.frame_2.setGeometry(QtCore.QRect(0, 410, 681, 131))
        self.frame_2.setObjectName(_fromUtf8("frame_2"))
        self.frame_5 = QtGui.QFrame(self.frame_2)
        self.frame_5.setGeometry(QtCore.QRect(320, 10, 231, 111))
        self.frame_5.setMinimumSize(QtCore.QSize(0, 0))
        self.frame_5.setMaximumSize(QtCore.QSize(9999999, 16777215))
        self.frame_5.setFrameShape(QtGui.QFrame.Box)
        self.frame_5.setFrameShadow(QtGui.QFrame.Sunken)
        self.frame_5.setObjectName(_fromUtf8("frame_5"))
        self.verticalLayout_4 = QtGui.QVBoxLayout(self.frame_5)
        self.verticalLayout_4.setObjectName(_fromUtf8("verticalLayout_4"))
        self.label_14 = QtGui.QLabel(self.frame_5)
        self.label_14.setObjectName(_fromUtf8("label_14"))
        self.verticalLayout_4.addWidget(self.label_14)
        self.label_16 = QtGui.QLabel(self.frame_5)
        self.label_16.setObjectName(_fromUtf8("label_16"))
        self.verticalLayout_4.addWidget(self.label_16)
        self.label_15 = QtGui.QLabel(self.frame_5)
        self.label_15.setObjectName(_fromUtf8("label_15"))
        self.verticalLayout_4.addWidget(self.label_15)
        self.le_realLength = QtGui.QLineEdit(self.frame_5)
        self.le_realLength.setMaximumSize(QtCore.QSize(100, 16777215))
        self.le_realLength.setObjectName(_fromUtf8("le_realLength"))
        self.verticalLayout_4.addWidget(self.le_realLength)
        self.frame_6 = QtGui.QFrame(self.frame_2)
        self.frame_6.setGeometry(QtCore.QRect(554, 10, 121, 111))
        self.frame_6.setMinimumSize(QtCore.QSize(0, 0))
        self.frame_6.setMaximumSize(QtCore.QSize(9999999, 16777215))
        self.frame_6.setFrameShape(QtGui.QFrame.Box)
        self.frame_6.setFrameShadow(QtGui.QFrame.Sunken)
        self.frame_6.setObjectName(_fromUtf8("frame_6"))
        self.verticalLayout_5 = QtGui.QVBoxLayout(self.frame_6)
        self.verticalLayout_5.setObjectName(_fromUtf8("verticalLayout_5"))
        self.pushButton = QtGui.QPushButton(self.frame_6)
        self.pushButton.setObjectName(_fromUtf8("pushButton"))
        self.verticalLayout_5.addWidget(self.pushButton)
        self.frame_4 = QtGui.QFrame(self.frame_2)
        self.frame_4.setGeometry(QtCore.QRect(10, 10, 307, 111))
        self.frame_4.setMinimumSize(QtCore.QSize(0, 0))
        self.frame_4.setMaximumSize(QtCore.QSize(307, 111))
        self.frame_4.setFrameShape(QtGui.QFrame.Box)
        self.frame_4.setFrameShadow(QtGui.QFrame.Sunken)
        self.frame_4.setObjectName(_fromUtf8("frame_4"))
        self.verticalLayout_3 = QtGui.QVBoxLayout(self.frame_4)
        self.verticalLayout_3.setObjectName(_fromUtf8("verticalLayout_3"))
        self.frame_3 = QtGui.QFrame(self.frame_4)
        self.frame_3.setMinimumSize(QtCore.QSize(0, 0))
        self.frame_3.setMaximumSize(QtCore.QSize(999, 999))
        self.frame_3.setObjectName(_fromUtf8("frame_3"))
        self.gridLayout_5 = QtGui.QGridLayout(self.frame_3)
        self.gridLayout_5.setObjectName(_fromUtf8("gridLayout_5"))
        self.sldr_Red = QtGui.QSlider(self.frame_3)
        self.sldr_Red.setMinimumSize(QtCore.QSize(84, 15))
        self.sldr_Red.setMaximumSize(QtCore.QSize(84, 15))
        self.sldr_Red.setMaximum(255)
        self.sldr_Red.setOrientation(QtCore.Qt.Horizontal)
        self.sldr_Red.setObjectName(_fromUtf8("sldr_Red"))
        self.gridLayout_5.addWidget(self.sldr_Red, 3, 0, 1, 1)
        self.label_5 = QtGui.QLabel(self.frame_3)
        self.label_5.setMinimumSize(QtCore.QSize(84, 14))
        self.label_5.setAlignment(QtCore.Qt.AlignCenter)
        self.label_5.setObjectName(_fromUtf8("label_5"))
        self.gridLayout_5.addWidget(self.label_5, 2, 0, 1, 1)
        self.label_12 = QtGui.QLabel(self.frame_3)
        self.label_12.setMinimumSize(QtCore.QSize(84, 14))
        self.label_12.setAlignment(QtCore.Qt.AlignCenter)
        self.label_12.setObjectName(_fromUtf8("label_12"))
        self.gridLayout_5.addWidget(self.label_12, 2, 2, 1, 1)
        self.label_13 = QtGui.QLabel(self.frame_3)
        self.label_13.setMinimumSize(QtCore.QSize(85, 14))
        self.label_13.setAlignment(QtCore.Qt.AlignCenter)
        self.label_13.setObjectName(_fromUtf8("label_13"))
        self.gridLayout_5.addWidget(self.label_13, 2, 1, 1, 1)
        self.sldr_Green = QtGui.QSlider(self.frame_3)
        self.sldr_Green.setMinimumSize(QtCore.QSize(85, 15))
        self.sldr_Green.setMaximumSize(QtCore.QSize(85, 15))
        self.sldr_Green.setMaximum(255)
        self.sldr_Green.setOrientation(QtCore.Qt.Horizontal)
        self.sldr_Green.setObjectName(_fromUtf8("sldr_Green"))
        self.gridLayout_5.addWidget(self.sldr_Green, 3, 1, 1, 1)
        self.sldr_Blue = QtGui.QSlider(self.frame_3)
        self.sldr_Blue.setMinimumSize(QtCore.QSize(84, 15))
        self.sldr_Blue.setMaximumSize(QtCore.QSize(84, 15))
        self.sldr_Blue.setMaximum(255)
        self.sldr_Blue.setOrientation(QtCore.Qt.Horizontal)
        self.sldr_Blue.setObjectName(_fromUtf8("sldr_Blue"))
        self.gridLayout_5.addWidget(self.sldr_Blue, 3, 2, 1, 1)
        self.lblColor = QLabel_Color(self.frame_3)
        self.lblColor.setMinimumSize(QtCore.QSize(32, 32))
        self.lblColor.setMaximumSize(QtCore.QSize(32, 32))
        self.lblColor.setFrameShape(QtGui.QFrame.Box)
        self.lblColor.setText(_fromUtf8(""))
        self.lblColor.setAlignment(QtCore.Qt.AlignCenter)
        self.lblColor.setObjectName(_fromUtf8("lblColor"))
        self.gridLayout_5.addWidget(self.lblColor, 0, 1, 1, 1, QtCore.Qt.AlignHCenter)
        self.verticalLayout_3.addWidget(self.frame_3)
        self.widget = QtGui.QWidget(self.wzdp_dimensionalRatio)
        self.widget.setGeometry(QtCore.QRect(0, 0, 2, 2))
        self.widget.setObjectName(_fromUtf8("widget"))
        self.verticalLayout_2 = QtGui.QVBoxLayout(self.widget)
        self.verticalLayout_2.setMargin(0)
        self.verticalLayout_2.setObjectName(_fromUtf8("verticalLayout_2"))
        QWizard_NewAnalysis.addPage(self.wzdp_dimensionalRatio)

        self.retranslateUi(QWizard_NewAnalysis)
        QtCore.QObject.connect(self.rb_fromFile, QtCore.SIGNAL(_fromUtf8("toggled(bool)")), self.frame_VideoPath.setVisible)
        QtCore.QMetaObject.connectSlotsByName(QWizard_NewAnalysis)

    def retranslateUi(self, QWizard_NewAnalysis):
        QWizard_NewAnalysis.setWindowTitle(_translate("QWizard_NewAnalysis", "Nova Análise", None))
        self.label_6.setText(_translate("QWizard_NewAnalysis", "Selecione o tipo de entrada de vídeo a ser utilizada na análise", None))
        self.rb_fromCamera.setText(_translate("QWizard_NewAnalysis", "Câmera", None))
        self.rb_fromFile.setText(_translate("QWizard_NewAnalysis", "Arquivo de Vídeo", None))
        self.label_2.setText(_translate("QWizard_NewAnalysis", "Caminho do Arquivo de Vídeo:", None))
        self.pb_searchFile.setText(_translate("QWizard_NewAnalysis", "...", None))
        self.pb_holdFrame.setText(_translate("QWizard_NewAnalysis", "Congelar Frame Atual", None))
        self.label_10.setText(_translate("QWizard_NewAnalysis", "Traçe uma linha de dimensões conhecidas na imagem utilizando o botão esquerdo. A roda do mouse e o botão direito podem ser utilizadas para alterar o zoom.", None))
        self.label_14.setText(_translate("QWizard_NewAnalysis", "Dimensão da linha em pixels:", None))
        self.label_16.setText(_translate("QWizard_NewAnalysis", "0", None))
        self.label_15.setText(_translate("QWizard_NewAnalysis", "Dimensão real da linha em cm:", None))
        self.pushButton.setText(_translate("QWizard_NewAnalysis", "Opções de Filtro", None))
        self.label_5.setText(_translate("QWizard_NewAnalysis", "R", None))
        self.label_12.setText(_translate("QWizard_NewAnalysis", "B", None))
        self.label_13.setText(_translate("QWizard_NewAnalysis", "G", None))

from QGraphicsView_LineMarker.QGraphicsView_LineMarker import QGraphicsView_LineMarker
from QWizardPage_DimensionalRatio import QWizardPage_DimensionalRatio
from QWizardPage_VideoInput import QWizardPage_VideoInput
from QLabel_Color import QLabel_Color
